# Generated by Django 5.2.9 on 2026-01-04 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10)),
                ('lot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ticket', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('magic', models.IntegerField(default=900001)),
                ('comment', models.CharField(blank=True, default='SniperATR-Live', max_length=64)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('sl', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('tp', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('closed', 'Closed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
