# Generated by Django 5.2.9 on 2026-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={},
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='ticket',
            new_name='order_ticket',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='trade',
            name='position_ticket',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='side',
            field=models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('open', 'OPEN'), ('closed', 'CLOSED'), ('failed', 'FAILED')], db_index=True, default='pending', max_length=10),
        ),
    ]
