# Generated by Django 5.2.9 on 2026-01-10 19:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_trade_status_tradeexecutionaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='side',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TradeAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('mt5_request_built', 'MT5 Request Built'), ('mt5_send_attempt', 'MT5 Send Attempt'), ('mt5_result', 'MT5 Result'), ('trade_updated', 'Trade Updated'), ('error', 'Error')], max_length=64)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request', models.JSONField(blank=True, null=True)),
                ('response', models.JSONField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_audit_events', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='trading.trade')),
            ],
        ),
    ]
