# Generated by Django 5.2.9 on 2026-01-10 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_trade_correlation_id_trade_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradeauditevent',
            options={'ordering': ['trade_id', 'seq']},
        ),
        migrations.AddField(
            model_name='trade',
            name='audit_seq',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradeauditevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tradeauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradeauditevent',
            name='event_type',
            field=models.CharField(choices=[('TRADE_CREATED', 'Trade created'), ('VALIDATION_OK', 'Validation ok'), ('VALIDATION_FAILED', 'Validation failed'), ('MT5_CONNECT_START', 'MT5 connect start'), ('MT5_CONNECT_OK', 'MT5 connect ok'), ('MT5_CONNECT_FAIL', 'MT5 connect fail'), ('SYMBOL_RESOLVE_START', 'Symbol resolve start'), ('SYMBOL_RESOLVED', 'Symbol resolved'), ('SYMBOL_NOT_FOUND', 'Symbol not found'), ('SYMBOL_NOT_SELECTABLE', 'Symbol not selectable'), ('TICK_FETCH', 'Tick fetch'), ('PRICE_SELECTED', 'Price selected'), ('SLIPPAGE_COMPUTED', 'Slippage computed'), ('ORDER_REQUEST_BUILT', 'Order request built'), ('ORDER_SEND_ATTEMPT', 'Order send attempt'), ('ORDER_SEND_RESULT', 'Order send result'), ('TRADE_STATUS_UPDATED', 'Trade status updated'), ('ERROR', 'Error')], max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='tradeauditevent',
            unique_together={('trade', 'seq')},
        ),
        migrations.AddIndex(
            model_name='tradeauditevent',
            index=models.Index(fields=['trade', 'seq'], name='trading_tra_trade_i_e726f8_idx'),
        ),
        migrations.AddIndex(
            model_name='tradeauditevent',
            index=models.Index(fields=['event_type', 'at'], name='trading_tra_event_t_6c5a1f_idx'),
        ),
    ]
