# Generated by Django 5.2.9 on 2026-01-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_tradeauditevent_options_trade_audit_seq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='audit_seq',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
