# Generated by Django 5.2.9 on 2026-01-11 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_trade_audit_seq'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeauditevent',
            name='hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tradeauditevent',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradeauditevent',
            name='prev_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tradeauditevent',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='tradeauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tradeauditevent',
            name='event_type',
            field=models.CharField(choices=[('TRADE_CREATED', 'Trade created'), ('VALIDATION_OK', 'Validation ok'), ('VALIDATION_FAILED', 'Validation failed'), ('MT5_CONNECT_START', 'MT5 connect start'), ('MT5_CONNECT_OK', 'MT5 connect ok'), ('MT5_CONNECT_FAIL', 'MT5 connect fail'), ('SYMBOL_RESOLVE_START', 'Symbol resolve start'), ('SYMBOL_RESOLVED', 'Symbol resolved'), ('SYMBOL_NOT_FOUND', 'Symbol not found'), ('SYMBOL_NOT_SELECTABLE', 'Symbol not selectable'), ('TICK_FETCH', 'Tick fetch'), ('PRICE_SELECTED', 'Price selected'), ('SLIPPAGE_COMPUTED', 'Slippage computed'), ('ORDER_REQUEST_BUILT', 'Order request built'), ('ORDER_SEND_ATTEMPT', 'Order send attempt'), ('ORDER_SEND_RESULT', 'Order send result'), ('TRADE_STATUS_UPDATED', 'Trade status updated'), ('ERROR', 'Error'), ('TRADE_UPDATED', 'Trade Updated'), ('MT5_ORDER_REQUEST', 'MT5 Order Request'), ('MT5_ORDER_RESULT', 'MT5 Order Result'), ('MT5_ORDER_FAILED', 'MT5 Order Failed')], db_index=True, max_length=64),
        ),
    ]
