# Generated by Django 5.2.9 on 2026-01-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_tradeauditevent_hash_tradeauditevent_ip_and_more'),
        ('trading', '00xx_backfill_audit_hashes'),
    ]

    operations = [
    ]
