# Generated by Django 5.2.9 on 2025-12-28 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_login', models.BigIntegerField(blank=True, null=True)),
                ('mt5_server', models.CharField(blank=True, max_length=100, null=True)),
                ('mt5_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mt5_equity', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('risk_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active_trader', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
