# Generated by Django 5.2.9 on 2026-01-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_mt5account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('server_keywords', models.JSONField(blank=True, default=list)),
                ('withdraw_url', models.URLField(blank=True, default='')),
                ('portal_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
