# trading/admin.py
from django.contrib import admin
from .models import Trade, TradeAuditEvent


class ReadOnlyAdminMixin:
    """Make admin screens read-only (view-only)."""

    def has_add_permission(self, request):
        return False

    def has_change_permission(self, request, obj=None):
        return False

    def has_delete_permission(self, request, obj=None):
        return False

    # Optional: still allow viewing objects (Django admin uses change view as "detail view")
    def get_readonly_fields(self, request, obj=None):
        if obj is None:
            return []
        # Make every field read-only on the detail page
        return [f.name for f in obj._meta.fields] + [f.name for f in obj._meta.many_to_many]


@admin.register(TradeAuditEvent)
class TradeAuditEventAdmin(ReadOnlyAdminMixin, admin.ModelAdmin):
    list_display = ("id", "trade_id", "seq", "event_type", "at", "actor_id", "ip_display")
    list_filter = ("event_type", "at")
    search_fields = ("trade__id", "trade__symbol", "ip", "user_agent")
    ordering = ("-at", "-id")

    # Good for performance on large tables:
    raw_id_fields = ("trade",)

    # If you have these fields in your model, keep them:
    # readonly_fields is auto-generated by mixin on detail view, but list view needs nothing.

    @admin.display(ordering="trade_id", description="Trade ID")
    def trade_id_display(self, obj):
        return obj.trade_id

    @admin.display(description="Actor ID")
    def actor_id_display(self, obj):
        # If your model field is actor = ForeignKey(User, null=True)
        actor = getattr(obj, "actor", None)
        return actor.id if actor else None

    @admin.display(description="IP")
    def ip_display(self, obj):
        # Try common names safely:
        return (
                getattr(obj, "ip_address", None)
                or getattr(obj, "ip", None)
                or getattr(obj, "ip_addr", None)
                or getattr(obj, "client_ip", None)
        )

@admin.register(Trade)
class TradeAdmin(ReadOnlyAdminMixin, admin.ModelAdmin):
    list_display = ("id", "user", "symbol", "side", "lot", "status", "created_at", "opened_at", "closed_at")
    list_filter = ("status", "symbol", "side")
    search_fields = ("id", "symbol", "user__username")
    ordering = ("-created_at", "-id")

    @admin.display(ordering="trade_id", description="Trade ID")
    def trade_id_display(self, obj):
        return obj.trade_id

    def has_change_permission(self, request, obj=None):
        if obj and obj.status == "closed":
            return False
        return super().has_change_permission(request, obj)