"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

from django.conf.global_settings import EMAIL_TIMEOUT
from pathlib import Path
from dotenv import load_dotenv
import os

BASE_DIR = Path(__file__).resolve().parent.parent.parent  # adjust if needed
load_dotenv(BASE_DIR / ".env")

#from trading.constants import MAX_LOT, ALLOWED_SYMBOLS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(f+mby@9fn(u&mim#wu^9(@7&kp2+*(wt$&%m2aj0@9&mg(hkg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    "django.contrib.sites",

    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    "dj_rest_auth",
    "dj_rest_auth.registration",
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    #'config.core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'trading',
    'channels',
    'config.trade_dashboard.apps.TradeDashboardConfig',
    #'trade_dashboard.apps.TradeDashboardConfig',
    'ai_assistant.apps.AiAssistantConfig',
    'corsheaders',
    'ai_assistant.journal',
    'notifications.apps.NotificationsConfig',
    # ...
    "rest_framework_simplejwt",
    # ...
    "security",

    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.twitter_oauth2",
    "anymail",


]
SITE_ID = 1

ACCOUNT_SETTINGS = {
    "EMAIL_REQUIRED": False,
    "UNIQUE_EMAIL": True,
    "USERNAME_REQUIRED": False,
    "AUTHENTICATION_METHOD": "email",
    "EMAIL_VERIFICATION": "mandatory",
}

SOCIALACCOUNT_EMAIL_VERIFICATION = "none"


ACCOUNT_UNIQUE_EMAIL = True


EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@yourapp.local")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

ANYMAIL = {
    "SENDGRID_API_KEY": os.getenv("SENDGRID_API_KEY", ""),
}

EMAIL_TIMEOUT = 10



TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")  # your bot token

EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
ANYMAIL = {
    "SENDGRID_API_KEY": os.getenv("SENDGRID_API_KEY", ""),
}
DEFAULT_FROM_EMAIL = "no-reply@yourdomain.com"
SERVER_EMAIL = "errors@yourdomain.com"
EMAIL_TIMEOUT = 10
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',

]

CELERY_BROKER_URL = "memory://" #os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND ="cache+memory://" #os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/0")
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_DEFAULT_RETRY_DELAY = 10
CELERY_TASK_MAX_RETRIES = 5


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ROOT_URLCONF = "config.core.urls"
WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        "CONFIG": {"hosts": [("redis://127.0.0.1", 6379)],},
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

OPENAI_API_KEY=[
    
]
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --- Web Push (VAPID) ---
WEBPUSH_VAPID_PUBLIC_KEY = "PASTE_PUBLIC_KEY"
WEBPUSH_VAPID_PRIVATE_KEY = "PASTE_PRIVATE_KEY"
WEBPUSH_VAPID_SUBJECT = "mailto:admin@example.com"

# --- Telegram ---
TELEGRAM_ENABLED = True

# --- Notification gating defaults ---
ALEX_NOTIFY_MIN_CONFIDENCE = 80
ALEX_NOTIFY_CONFIRMED_ONLY = True
ALEX_NOTIFY_COOLDOWN_SECONDS = 900  # 15 mins per symbol+tf+side

VAPID_PUBLIC_KEY = "0x000001BB53B5D370"
VAPID_PRIVATE_KEY = "0x000001BB53B5D930"
VAPID_CLAIMS = {"sub": "mailto:admin@yourapp.com"}

# --- Web Push (VAPID) ---
WEBPUSH_ENABLED = True

ALEX_EXECUTION_ENABLED = False        # start safe
ALEX_EXECUTION_MODE = "PAPER"         # PAPER or LIVE
ALEX_EXECUTION_REQUIRE_CONFIRMED = True
ALEX_EXECUTION_MIN_CONFIDENCE = 80

# Generate these keys once (instructions below)
WEBPUSH_VAPID_CLAIMS = {

    "sub": "mailto:admin@yourdomain.com",
}

# --- Alex notify gating defaults ---
ALEX_NOTIFY_ENABLED = True


# OTP brute-force protection
OTP_GUARD = {
    "USER_MAX_ATTEMPTS": 6,          # wrong attempts before user lock
    "USER_WINDOW_SECONDS": 300,      # count attempts in last 5 mins
    "USER_LOCK_SECONDS": 900,        # lock user for 15 mins

    "IP_MAX_ATTEMPTS": 15,           # wrong attempts before IP lock
    "IP_WINDOW_SECONDS": 300,        # count attempts in last 5 mins
    "IP_LOCK_SECONDS": 900,          # lock IP for 15 mins
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

TWOFA_ISSUER_NAME = "SniperATR Pro"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASS': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ),

    'DEFAULT_THROTTLE_RATES': {
        "user": "60/min",
        "anon": "10/min",
        "analyze": "20/min",
        "execute": "5/min",
        "alex_analyze": "20/min",
    },
}
USE_JWT = True
CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@yourapp.local"


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


CORS_ALLOWED_CREDENTIALS = False

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5173",
    "http://localhost:5173",
]

TRADING_ENABLED = True
MAX_LOT = 1.0
ALLOWED_SYMBOLS = [ "EURUSD",
    "GBPUSD",
    "USDJPY",
    "USDCHF",
    "AUDUSD",
    "USDCAD",
    "NZDUSD",

    # Cross Pairs (Highly Traded)
    "EURGBP",
    "EURJPY",
    "GBPJPY",

    # Indices
    "US30",     # Dow Jones
    "NAS100",   # Nasdaq 100
    "SPX500",   # S&P 500
    "GER40",    # DAX 40

    # Commodities
    "XAUUSD",   # Gold
    "XAGUSD",   # Silver
    "WTI",      # Crude Oil
    "BRENT",    # Brent Oil

    # Crypto
    "BTCUSD",
    "ETHUSD"]
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# --- Alex execution safety ---
ALEX_LIVE_EXECUTION_ENABLED = False  # keep False until you're 100% ready
ALEX_MIN_CONFIDENCE_TO_EXECUTE = 80
ALEX_MAX_VOLUME = 0.05
ALEX_EXECUTION_COOLDOWN_SECONDS = 60
ALEX_ALLOWED_SYMBOLS = ["XAUUSD", "EURGBP", "GBPUSD"]
ALEX_ALLOWED_TIMEFRAMES = ["M5", "M15", "M30", "H1"]

REAUTH = {
    "TTL_SECONDS": 600,  # 10 minutes
}

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@yourapp.local"
FRONTEND_RESET_URL = "http://localhost:3000/reset-password"  # your frontend page

import allauth.account.app_settings as allauth_settings
if "EMAIL_REQUIRED" in globals():
    raise RuntimeError("Remove EMAIL_REQUIRED from settings; use ACCOUNT_EMAIL_REQUIRED instead.")

