# Generated by Django 5.2.9 on 2026-01-20 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushsubscription',
            name='last_seen_at',
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('confirmed_only', models.BooleanField(default=True)),
                ('min_confidence', models.PositiveSmallIntegerField(default=80)),
                ('symbols_csv', models.CharField(blank=True, default='', max_length=500)),
                ('timeframe_bucket', models.CharField(blank=True, choices=[('FAST', 'Fast/Short'), ('MEDIUM', 'Medium'), ('LONG', 'Long term')], default='', max_length=10)),
                ('cooldown_seconds', models.PositiveIntegerField(default=900)),
                ('max_per_hour', models.PositiveSmallIntegerField(default=6)),
                ('webpush_enabled', models.BooleanField(default=True)),
                ('telegram_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notify_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(blank=True, default='', max_length=20)),
                ('channel', models.CharField(default='webpush', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'symbol', 'timeframe', 'created_at'], name='notificatio_user_id_0345a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timeframe', models.CharField(max_length=10)),
                ('side', models.CharField(max_length=10)),
                ('confidence', models.PositiveIntegerField(default=0)),
                ('entry', models.FloatField(blank=True, null=True)),
                ('sl', models.FloatField(blank=True, null=True)),
                ('tp1', models.FloatField(blank=True, null=True)),
                ('tp2', models.FloatField(blank=True, null=True)),
                ('tp3', models.FloatField(blank=True, null=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('webpush_sent', models.BooleanField(default=False)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'fingerprint'], name='notificatio_user_id_488e42_idx')],
            },
        ),
    ]
