# Generated by Django 5.2.9 on 2026-01-20 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_pushsubscription_last_seen_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationdelivery',
            name='notificatio_user_id_0345a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='signalevent',
            name='notificatio_user_id_488e42_idx',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='confirmed_only',
            new_name='execution_alerts_enabled',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='enabled',
            new_name='signal_alerts_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationdelivery',
            name='symbol',
        ),
        migrations.RemoveField(
            model_name='notificationdelivery',
            name='timeframe',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='cooldown_seconds',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='max_per_hour',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='min_confidence',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='symbols_csv',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='timeframe_bucket',
        ),
        migrations.RemoveField(
            model_name='signalevent',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='signalevent',
            name='fingerprint',
        ),
        migrations.RemoveField(
            model_name='signalevent',
            name='side',
        ),
        migrations.RemoveField(
            model_name='signalevent',
            name='telegram_sent',
        ),
        migrations.RemoveField(
            model_name='signalevent',
            name='webpush_sent',
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='signalevent',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('WEBPUSH', 'WEBPUSH'), ('TELEGRAM', 'TELEGRAM')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='signalevent',
            name='confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='signalevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='signalevent',
            name='symbol',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='signalevent',
            name='timeframe',
            field=models.CharField(max_length=16),
        ),
    ]
